version: "3.9"
services:

  mongo:
    image: $IMAGES_MONGO
    network_mode: host
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db 

  postgis:
    image: $IMAGES_POSTGIS
    network_mode: host
    container_name: postgis
    restart: unless-stopped
    volumes:
      - postgis_data:/var/lib/postgresql
    deploy:
      resources:
        # limits or reservations ?
        reservations:
          memory: 8G

  rabbitmq:
    image: $IMAGES_RABBITMQ
    network_mode: host
    container_name: rabbitmq
    restart: unless-stopped

  bioformat:
    image: $IMAGES_BIOFORMAT
    network_mode: host
    container_name: bioformat
    restart: unless-stopped
    volumes:
      - $HOST_PATHS_IMAGES:$CONTAINER_PATHS_IMAGES

  pims-cache:
    image: $IMAGES_PIMS_CACHE
    network_mode: host
    container_name: pims-cache
    restart: unless-stopped

  pims: 
    image: $IMAGES_PIMS
    network_mode: host
    container_name: pims
    restart: unless-stopped
    depends_on:
      - pims-cache
      - rabbitmq
    volumes:
      - $HOST_PATHS_IMAGES:$CONTAINER_PATHS_IMAGES
      - $HOST_PATHS_IMAGES_BUFFER:$CONTAINER_PATHS_UPLOADED  # why subpath of /data/images rather than another path ???
    deploy:
      resources:
        # limits or reservations ?
        reservations:
          memory: 4G

  web_ui:
    image: $IMAGES_WEB_UI
    network_mode: host
    container_name: web_ui
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime

  nginx:
    image: $IMAGES_NGINX
    network_mode: host
    container_name: nginx
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - web_ui
      - pims
    volumes:
      - $HOST_PATHS_IMAGES_BUFFER:$CONTAINER_PATHS_UPLOADED

  # to map nginx ip with urls to host's /etc/hosts
  etc_hosts_rewriter:
    image: alpine:latest
    network_mode: host
    entrypoint: ["/bin/sh", "/cm_configs/rewrite.sh"]
    depends_on:
      - nginx
    volumes:
      - /etc:/local_etc/

volumes:
  mongo_data:
  postgis_data:
