version: "3.9"
services:

  mongo:
    image: $IMAGES_MONGO
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 

  postgis:
    image: $IMAGES_POSTGIS
    container_name: postgis
    restart: unless-stopped
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - postgis_data:/var/lib/postgresql
    deploy:
      resources:
        # limits or reservations ?
        reservations:
          memory: 8G

  rabbitmq:
    image: $IMAGES_RABBITMQ
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  bioformat:
    image: $IMAGES_BIOFORMAT
    container_name: bioformat
    restart: unless-stopped
    ports:
      - "4321:4321"
    volumes:
      - $HOST_PATHS_IMAGES:$CONTAINER_PATHS_IMAGES

  pims-cache:
    image: $IMAGES_PIMS_CACHE
    container_name: pims-cache
    restart: unless-stopped

  pims: 
    image: $IMAGES_PIMS
    container_name: pims
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - pims-cache
      - rabbitmq
    volumes:
      - $HOST_PATHS_IMAGES:$CONTAINER_PATHS_IMAGES
      - $HOST_PATHS_IMAGES_BUFFER:$CONTAINER_PATHS_UPLOADED  # why subpath of /data/images rather than another path ???
    deploy:
      resources:
        # limits or reservations ?
        reservations:
          memory: 4G

  web_ui:
    build:
      context: $HOST_PATHS_WEB_UI_SRC
      dockerfile: docker/Dockerfile
      target: dev-server
      args:
        SCRIPTS_REPO_TAG: latest
    ports:
      - "$WEB_UI_PORT:$WEB_UI_PORT"
    working_dir: "/app"
    container_name: web_ui
    restart: unless-stopped
    volumes:
      - $HOST_PATHS_WEB_UI_SRC:/app
      - /etc/localtime:/etc/localtime

  nginx:
    image: $IMAGES_NGINX
    container_name: nginx
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
    depends_on:
      - web_ui
      - pims
    volumes:
      - $HOST_PATHS_IMAGES_BUFFER:$CONTAINER_PATHS_UPLOADED

  # to map nginx ip with urls to host's /etc/hosts
  etc_hosts_rewriter:
    image: alpine:latest
    entrypoint: ["/bin/sh", "/cm_configs/rewrite.sh"]
    depends_on:
      - nginx
    volumes:
      - /etc:/local_etc/

volumes:
  mongo_data:
  postgis_data:
